ch new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
###

fibo = (x)-> if(x>1) then fibo(x-1)+fibo(x-2) else x

total=0
for x in [1..33]
  y=fibo(x)
  if y%2==0 then total=total+y

alert total
